[package]
name = "convert-af"
version = "0.1.0"
edition = "2021"

[dependencies]
af-anndata = { path = "../af-anndata" }
anyhow = "1.0.95"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
